### PR TITLE
Some features added and rewritten readme

### PR DESCRIPTION
**Pull request by captain1242**
Hi mcNuggets. I saw your script and made some improvements you may like ;)

### CODE REVIEW

**Comment by mcNuggets1** [comment]
Actually this script was made as a joke.

However you made some cool edits, but not all of them should be merged.

You didn't follow my code style either.
Doesn't look unite, this way.

The read me idea is good.
The saving of ids/ips seems rather useless however.
Does not make mich sende for me, if you hate a guy enough, you Could just edit the script config rather a file.

Adding a steamid to the Blacklist is Useful and I will integrate it for sure, checking for already exisiting ips and not merging already existing in the table is good either, but not to run a Timer to check, there are Way better ways to do this.

Well thanks for the Push Request, I will consider adding some of these ideas and work, but the Push Request right now is too messy for me to merge.

**Comment by mcNuggets1** [comment]
Can't fix my Spelling mistakes due to mobile Version :<

**Comment by captain1242** [comment]
I know it was a joke script ... but I thought its an good idea for some players :) But the saving of the alts and IPs was added due that if I don't save them somewhere there are gone after a restart what I wanted to prevent. The timer every 5 minutes is to check all online players if there were changes .. I know I could intigrate that in the command but hey I made those changes in 10 minutes :) For the code style: Meh I know I am sometimes switching styles but thats cause I am thinking how to code the next function I want to add while I am programming an other function .. that messes the code sometimes up.
Also I just saw that the player checker won't work .. I forgot to add the for loop.

By the way wieso schreibe ich eigentlich in Englisch? XD

**Comment by mcNuggets1** [comment]
Well

**Comment by mcNuggets1** [comment]
You can create a new pull request with the readme update, if you like to.

**Comment by captain1242** [comment]
Ok mach ich später ;)

**Pull request closed without merging**
